# action.yml
name: 'Rust Cargo Deb Package Build (amd64, Ubuntu)'
description: 'Builds a statically linked .deb package, amd64, musl, ubuntu'
branding:
  icon: 'package'
  color: 'orange'
runs:
  using: 'docker'
  image: 'docker://rincewindwizzard/cargo-deb-amd64-alpine:v3'
